import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {build} from 'esbuild';
const id='00000000-0000-4000-8000-000000000001';const library='00000000-0000-4000-8000-000000000002';
const fakeModules={settings:'export async function settings(){return structuredClone(prefs)};export async function saveSettings(update){const patch=typeof update==="function"?update(structuredClone(prefs)):update;prefs={...prefs,...patch};return prefs}',storage:'export async function recording(id){return records.get(id)}',protocol:'export class ProtocolError extends Error{constructor(message,status=0){super(message);this.status=status}};globalThis.PE=ProtocolError;export async function jsonRequest(...args){return wire(...args)}'};
const built=await build({entryPoints:['extension/src/connection.ts'],bundle:true,write:false,format:'iife',globalName:'api',plugins:[{name:'trusted-controls',setup(builder){builder.onResolve({filter:/^\.\/(settings|storage|protocol)$/},args=>({path:args.path.slice(2),namespace:'mock'}));builder.onLoad({filter:/.*/,namespace:'mock'},args=>({contents:fakeModules[args.path]}));}}]});
function harness(){let now=10000;const context={structuredClone,AbortSignal,Map,Set,Array,Number,Promise,Date:class extends Date{static now(){return now}},prefs:{installationId:id,activeLibraryId:library,pairs:{[library]:{libraryId:library,endpoint:'http://localhost:3000',credential:'synthetic-secret'}}},records:new Map([[id,{recordingId:id,libraryId:library,liveTranscription:true,chunkCount:1,totalFrames:16000}]]),wire:async()=>({libraryId:library,installationId:id})};vm.runInNewContext(built.outputFiles[0].text,context);return {context,api:context.api,advance:()=>{now+=6000},error:status=>new context.PE('synthetic unavailable',status)};}
test('connection checks distinguish reachable, unavailable and revoked without exposing credentials',async()=>{
  const h=harness();let calls=0;h.context.wire=async(_endpoint,path,options,credential)=>{calls++;assert.equal(path,'/connection');assert.ok(options.signal);assert.equal(credential,'synthetic-secret');return {libraryId:library,installationId:id}};
  assert.equal((await h.api.connectionStatus()).status,'connected');await h.api.connectionStatus();assert.equal(calls,1);
  h.advance();h.context.wire=async()=>{throw h.error(0)};assert.equal((await h.api.connectionStatus()).status,'unavailable');
  h.advance();h.context.wire=async()=>{throw h.error(401)};const revoked=await h.api.connectionStatus();assert.equal(revoked.status,'revoked');assert.equal(JSON.stringify(revoked).includes('synthetic-secret'),false);
});
test('disconnect requires confirmation and retains pairing/audio when revocation cannot be verified',async()=>{
  const h=harness();await assert.rejects(h.api.disconnect(false),/Confirm disconnect/);h.context.wire=async()=>{throw h.error(0)};await assert.rejects(h.api.disconnect(true),/could not confirm revocation/);assert.equal(h.context.prefs.activeLibraryId,library);assert.equal(h.context.prefs.pairs[library].credential,'synthetic-secret');assert.equal(h.context.records.size,1);
});
test('successful or previously revoked disconnect removes only that pairing and preserves local audio',async()=>{
  for(const alreadyRevoked of [false,true]){const h=harness();h.context.prefs.pairs.other={libraryId:'other',credential:'other-secret'};h.context.wire=async(_endpoint,path,options)=>{assert.equal(path,'/connection');assert.equal(options.method,'DELETE');if(alreadyRevoked)throw h.error(401);return {status:'disconnected'}};assert.equal((await h.api.disconnect(true)).status,'disconnected');assert.equal(h.context.prefs.activeLibraryId,null);assert.equal(h.context.prefs.pairs[library],undefined);assert.equal(h.context.prefs.pairs.other.credential,'other-secret');assert.equal(h.context.records.size,1);}
});
test('disconnect cannot erase a concurrently replaced credential or claim a stale check is connected',async()=>{
  const h=harness();h.context.wire=async()=>{h.context.prefs.pairs[library].credential='replacement';return {status:'disconnected'}};await h.api.disconnect(true);assert.equal(h.context.prefs.pairs[library].credential,'replacement');
  h.context.wire=async()=>{h.context.prefs.activeLibraryId=null;return {libraryId:library,installationId:id}};assert.equal((await h.api.connectionStatus()).status,'not-connected');
});
test('live preview is scoped, Unicode bounded, and excludes draft/credentials/controls',async()=>{
  const h=harness();h.context.wire=async(_endpoint,path)=>{assert.equal(path,`/recordings/${id}/live`);return {recordingId:id,libraryId:library,status:'live',preview:'🎙'.repeat(800),backlogSeconds:2,provisional:true,draft:{words:['private']},credential:'synthetic-secret',controls:[{action:'stop'}]}};
  const result=await h.api.livePreview(id);assert.equal(Array.from(result.preview).length,600);assert.equal(result.provisional,true);assert.equal(result.draft,undefined);assert.equal(result.credential,undefined);assert.equal(result.controls,undefined);
  h.context.wire=async()=>({recordingId:id,libraryId:'wrong-library',status:'live',preview:'private',backlogSeconds:0,provisional:false});assert.equal((await h.api.livePreview(id)).status,'unavailable');assert.equal((await h.api.livePreview(id)).preview,'');
});
test('live preview preserves optional-off behavior and reports offline, pending ingest and revocation',async()=>{
  const h=harness();for(const [code,status] of [[0,'unavailable'],[404,'waiting-audio'],[401,'revoked'],[410,'deleted']]){h.context.wire=async()=>{throw h.error(code)};assert.equal((await h.api.livePreview(id)).status,status);}
  h.context.records.get(id).liveTranscription=false;h.context.wire=async()=>{throw new Error('optional off must not fetch')};assert.equal((await h.api.livePreview(id)).status,'disabled');await assert.rejects(h.api.livePreview('../connection'),/Invalid recording/);
});
test('connection actions remain serialized across pairing/disconnect and recover from errors',async()=>{
  const h=harness();const order=[];await Promise.all([h.api.connectionAction(async()=>{order.push('first-start');await Promise.resolve();order.push('first-end')}),h.api.connectionAction(async()=>{order.push('second')})]);assert.deepEqual(order,['first-start','first-end','second']);await assert.rejects(h.api.connectionAction(async()=>{throw new Error('failed')}));assert.equal(await h.api.connectionAction(async()=>42),42);
});
async function settle(){for(let i=0;i<3;i++)await new Promise(resolve=>setImmediate(resolve));}
test('popup polls bounded live/connection status separately and renders exclusion without stopping capture',async()=>{
  const elements=new Map();const element=id=>{if(!elements.has(id))elements.set(id,{textContent:'',checked:false,hidden:false,value:'',listeners:{},append(){},addEventListener(name,callback){this.listeners[name]=callback}});return elements.get(id)};
  const intervals=new Map();const calls=[];const context={URL,element,document:{createElement:()=>({})},navigator:{mediaDevices:{enumerateDevices:async()=>[]}},chrome:{tabs:{query:async()=>[{id:7,url:'https://meet.google.com/abc-defg-hij'}]}},connection:'unavailable',live:{recordingId:id,status:'paused-open-echo',preview:'Short draft',backlogSeconds:4,provisional:true},active:{recordingId:id,mic:'Excluded · muted',micCaptured:true,micAvailable:true,micExcluded:false},setInterval(callback,ms){intervals.set(ms,callback)}};
  context.request=async message=>{calls.push(message);if(message.type==='CONNECTION_STATUS')return {status:context.connection};if(message.type==='LIVE_PREVIEW')return context.live;if(message.type==='MIC_EXCLUSION'){context.active.micExcluded=message.excluded;return {}};return {settings:{activeLibraryId:library,enabledProviders:['meet'],micGranted:true},active:context.active,recordings:[{recordingId:id,liveTranscription:true,totalFrames:16000}]}};
  const fakeUI='export const element=globalThis.element;export const request=globalThis.request;export const showError=e=>{throw e};export const action=async fn=>fn();export const renderRecordings=()=>{};export const duration=()=>"00:01"';
  const result=await build({entryPoints:['extension/src/popup.ts'],bundle:true,write:false,format:'iife',plugins:[{name:'popup-status',setup(builder){builder.onResolve({filter:/^\.\/ui$/},()=>({path:'ui',namespace:'mock'}));builder.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:fakeUI}));}}]});vm.runInNewContext(result.outputFiles[0].text,context);await settle();intervals.get(5000)();await settle();
  assert.match(element('connection').textContent,/Echo unavailable/);assert.match(element('live-status').textContent,/paused · open Echo/);assert.equal(element('live-preview').textContent,'Short draft');assert.equal(element('live-panel').hidden,false);assert.equal(element('mic-exclusion-field').hidden,false);
  element('mic-exclusion').checked=true;element('mic-exclusion').listeners.change();await settle();assert.ok(calls.some(message=>message.type==='MIC_EXCLUSION'&&message.recordingId===id&&message.excluded));assert.equal(calls.some(message=>message.type==='CONTROL'),false);
  context.connection='revoked';context.live={...context.live,status:'final-transcript-needed',preview:'',provisional:false};intervals.get(5000)();await settle();assert.match(element('connection').textContent,/revoked/);assert.match(element('live-status').textContent,/open Echo to create final transcript/);assert.equal(element('live-provisional').hidden,true);
});
test('setup disconnect warns about retained pending audio, honors cancel and reports offline revocation failure',async()=>{
  const elements=new Map();const element=id=>{if(!elements.has(id))elements.set(id,{textContent:'',value:'',hidden:true,listeners:{},append(){},replaceChildren(){},addEventListener(name,callback){this.listeners[name]=callback}});return elements.get(id)};
  let confirm=false;let warning='';let offline=true;let paired=true;const calls=[];const errors=[];
  const context={URLSearchParams,location:{hash:''},element,document:{createElement:()=>({append(){},addEventListener(){}})},window:{confirm(message){warning=message;return confirm},addEventListener(){}},setInterval(){},connection:'unavailable'};
  context.request=async message=>{calls.push(message);if(message.type==='CONNECTION_STATUS')return {status:paired?'unavailable':'not-connected'};if(message.type==='DISCONNECT'){if(offline)throw new Error('Echo could not confirm revocation. The connection is retained.');paired=false;return {status:'disconnected'}};return {settings:{activeLibraryId:paired?library:null,enabledProviders:[],micGranted:false,endpoint:'http://localhost:3000'},recordings:[{recordingId:id,libraryId:library,chunkCount:1}],active:null}};
  context.showError=error=>errors.push(error.message);
  const fakeUI='export const element=globalThis.element;export const request=globalThis.request;export const showError=globalThis.showError;export async function action(fn){try{await fn()}catch(error){showError(error)}};export const renderRecordings=()=>{}';
  const result=await build({entryPoints:['extension/src/setup.ts'],bundle:true,write:false,format:'iife',plugins:[{name:'setup-disconnect',setup(builder){builder.onResolve({filter:/^\.\/(ui|storage)$/},args=>({path:args.path.slice(2),namespace:'mock'}));builder.onLoad({filter:/.*/,namespace:'mock'},args=>({contents:args.path==='ui'?fakeUI:'export async function allRecordings(){return []};export async function* exportParts(){};export async function recording(){}'}));}}]});vm.runInNewContext(result.outputFiles[0].text,context);await settle();
  element('disconnect').listeners.click();assert.match(warning,/1 recording still need transfer/);assert.match(warning,/Local audio will be retained/);assert.equal(calls.some(message=>message.type==='DISCONNECT'),false);
  confirm=true;element('disconnect').listeners.click();await settle();assert.match(errors.at(-1),/connection is retained/);assert.equal(element('disconnect').hidden,false);assert.equal(element('status').textContent,'');
  offline=false;element('disconnect').listeners.click();await settle();assert.equal(element('disconnect').hidden,true);assert.match(element('status').textContent,/Disconnected/);assert.match(element('connection-status').textContent,/Not connected/);
});
test('AudioWorklet exclusion persists across provider gates and inclusion requires a new positive gate',async()=>{
  const result=await build({entryPoints:['extension/src/worklet.ts'],bundle:true,write:false,format:'iife'});let Processor;const sent=[];class Base{port={onmessage:null,postMessage:message=>sent.push(message)}};
  const context={AudioWorkletProcessor:Base,registerProcessor:(_name,type)=>{Processor=type},sampleRate:16000,currentTime:0,Date:{now:()=>1000},Float32Array,Int16Array,ArrayBuffer,DataView,Number,Math};vm.runInNewContext(result.outputFiles[0].text,context);const processor=new Processor({processorOptions:{recordingId:id}});let revision=0;let exclusionRevision=0;
  const message=data=>processor.port.onmessage({data});const gate=allowed=>message({type:'gate',recordingId:id,gateRevision:++revision,allowed,ttlMs:2000,expiresAt:3000});const exclude=excluded=>message({type:'exclude-mic',recordingId:id,exclusionRevision:++exclusionRevision,excluded});
  const pcm=()=>{processor.process([[new Float32Array(128)],[new Float32Array(128).fill(1)]],[[new Float32Array(128)]]);message({type:'pause',requestId:'flush'});const chunk=sent.splice(0).find(item=>item.type==='pcm');message({type:'resume'});return [...new Int16Array(chunk.pcm)].slice(1)};
  gate(true);assert.ok(pcm().some(value=>value>0));exclude(true);gate(true);assert.ok(pcm().every(value=>value===0));exclude(false);assert.ok(pcm().every(value=>value===0));gate(false);assert.ok(pcm().every(value=>value===0));gate(true);assert.ok(pcm().some(value=>value>0));
  message({type:'exclude-mic',recordingId:'different-recording',exclusionRevision:999,excluded:true});gate(true);assert.ok(pcm().some(value=>value>0));message({type:'exclude-mic',recordingId:id,exclusionRevision:1,excluded:true});gate(true);assert.ok(pcm().some(value=>value>0));
});
test('a local deletion winning a pending transfer status update does not abort other recordings; storage failures still propagate',async()=>{
  const fakeStorage='export async function allRecordings(){return [...records.values()]};export async function recording(id){return records.get(id)};export async function updateRecording(id,patch){if(deleteOnUpdate===id){records.delete(id);deleteOnUpdate=null}if(storageFailure)throw new Error("disk write failed");const row=records.get(id);if(!row)throw new Error("Recording not found");const next={...row,...patch};records.set(id,next);return next};export async function getChunk(){return {frames:1,pcm:new ArrayBuffer(2),sha256:"a".repeat(64)}};export async function retainReceiptAndRemovePCM(id,receipt){records.set(id,{...records.get(id),receipt})}';
  const result=await build({entryPoints:['extension/src/protocol.ts'],bundle:true,write:false,format:'iife',globalName:'api',plugins:[{name:'transfer-delete-race',setup(builder){builder.onResolve({filter:/^\.\/storage$/},()=>({path:'storage',namespace:'mock'}));builder.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:fakeStorage}));}}]});
  const newer={recordingId:'deleted',libraryId:library,chunkCount:1,totalFrames:1,captureState:'stopped',createdAt:'2026-01-01',gaps:[]};const older={...newer,recordingId:'remaining',createdAt:'2025-01-01'};let uploaded=false;let complete=false;
  const context={URL,Headers,Response,AbortSignal,Date,Promise,Map,ArrayBuffer,records:new Map([[newer.recordingId,newer],[older.recordingId,older]]),deleteOnUpdate:newer.recordingId,storageFailure:false,navigator:{locks:{request:async(_name,_options,work)=>work()}},fetch:async url=>{if(url.includes('/chunks/'))uploaded=true;if(url.endsWith('/complete'))complete=true;return new Response(JSON.stringify({protocolVersion:1,recordingId:older.recordingId,libraryId:library,meetingId:id,status:complete?'complete':'receiving',nextSequence:uploaded?1:0,totalFrames:uploaded?1:0}))}};
  vm.runInNewContext(result.outputFiles[0].text,context);const prefs={pairs:{[library]:{libraryId:library,endpoint:'http://localhost:3000',credential:'synthetic'}},activeLibraryId:library};await context.api.transferPending(prefs,async()=>{},()=>{});assert.ok(context.records.get(older.recordingId).receipt);assert.equal(context.records.has(newer.recordingId),false);
  context.records.set(newer.recordingId,newer);context.storageFailure=true;await assert.rejects(context.api.transferPending(prefs,async()=>{},()=>{}),/disk write failed/);
});
